name: v1-periphery

plugins:
  - name: alchemy
    version: 0.6.2
  - name: etherscan
    version: 0.6.7
  - name: solidity
    version: 0.6.9
  - name: foundry
    version: 0.6.12
  - name: arbitrum
    version: 0.6.1

default_ecosystem: ethereum

ethereum:
  default_network: local
  local:
    default_provider: foundry

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.3
  - name: uniswap-v3-core
    github: Uniswap/v3-core
    ref: 0.8
  - name: uniswap-v3-periphery
    github: Uniswap/v3-periphery
    ref: 0.8
  - name: marginal-v1-core
    local: ../v1-core

solidity:
  via_ir: true
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.3"
    - "@uniswap/v3-core/contracts=uniswap-v3-core/v0.8"
    - "@uniswap/v3-periphery/contracts=uniswap-v3-periphery/v0.8"
    - "@marginal/v1-core/contracts=marginal-v1-core/v1.0.0-beta.13"
